frase = str(input('Digite uma frase: ')).strip().lower()
y = frase.count('a')
print('A letra a aparece {} na frase'.format(y))
print('A primeira letra a aparece na posição {}'.format(frase.find('a')+1))
print('A primeira letra a aparece na posição {}'.format(frase.rfind('a')+1))
